---
- name: Firewall k8s configs
  ansible.builtin.include_tasks: firewall.yml

- name: Download k3s binary
  ansible.builtin.include_tasks: download.yml

- name: Sysctl k8s configs
  ansible.builtin.include_tasks: sysctl.yml
