---
- name: System k8s configs
  ansible.builtin.include_tasks: sys.yml

- name: Firewall k8s configs
  ansible.builtin.include_tasks: firewall.yml

- name: Sysctl k8s configs
  ansible.builtin.include_tasks: sysctl.yml

- name: Containerd k8s configs
  ansible.builtin.include_tasks: containerd.yml

- name: Kube k8s configs
  ansible.builtin.include_tasks: kube.yml
