---
- name: Install prometheus node exporter
  ansible.builtin.package:
    state: present
    name: prometheus-node-exporter

- name: Enable prometheus node exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    enabled: true
    state: started
