---
- name: Remove swapfile from /etc/fstap
  ansible.posix.mount:
    fstype: swap
    state: absent
    name:
      - swap
      - none

- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Modprobe modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - br_netfilter
    - overlay
