# Has my account & relevant details
---
- name: Create sudo group
  ansible.builtin.group:
    name: sudo
    state: present

- name: Create main user
  ansible.builtin.user:
    name: kwkaiser
    state: present
    comment: Karl's account
    shell: /bin/bash
    append: true
    groups:
      - sudo

- name: Create ssh dir if missing
  ansible.builtin.file:
    mode: "0700"
    dest: /home/kwkaiser/.ssh
    state: directory
    owner: kwkaiser
    group: kwkaiser

- name: Copy authorized keys
  ansible.builtin.copy:
    force: true
    mode: "0600"
    src: authorized_keys
    dest: /home/kwkaiser/.ssh/authorized_keys
