---
- hosts: all
  name: Setup common utils shared on all
  become: true
  roles:
    - knows_me
    # - hardened
    - comfy
    - geerlingguy.containerd
    - kubed

# - hosts: homelab-mainarray
#   name: Setup zfs on storage array
#   become: true
#   vars_files:
#     - zfs.yml
#   roles:
#     - mrlesmithjr.zfs

- hosts: heads
  name: Setup kubernetes cluster head
  become: true
  roles:
    - geerlingguy.kubernetes
  vars:
    kubernetes_role: "control_plane"

- hosts: nodes
  name: Setup kubernetes cluster nodes
  become: true
  roles:
    - geerlingguy.kubernetes
  vars:
    kubernetes_role: "node" 