---
- hosts: all
  name: Setup common utils shared on all
  become: true
  roles:
    - comfy
    - knows_me
    - hardened
    - kubed

- hosts: homelab-mainarray
  name: Setup zfs on storage array
  become: true
  vars_files:
    - zfs.yml
  roles:
    - mrlesmithjr.zfs
    - storage_array

- hosts: homelab-thinkcentre
  name: Setup kubernetes cluster head
  become: true
  roles:
    - kubed_head

- hosts: homelab-mainarray
  name: Setup kubernetes nodes
  become: true
  roles:
    - kubed_node
