---
- name: Setup common utils shared on all
  hosts: all
  become: true
  vars_files:
    - k3s.yml
  roles:
    - comfy
    - knows_me
    - hardened
    - kubed

- name: Setup zfs on storage array
  hosts: homelab-mainarray
  become: true
  vars_files:
    - zfs.yml
  roles:
    - storage_array

- name: Setup kubernetes cluster head
  hosts: homelab-thinkcentre
  become: true
  vars_files:
    - k3s.yml
  roles:
    - kubed_head

- name: Setup kubernetes nodes
  hosts: homelab-mainarray
  become: true
  vars_files:
    - k3s.yml
  roles:
    - kubed_node
