---
- name: Setup common utils shared on all
  hosts: all
  become: true
  vars_files:
    - ./vars/k3s.yml
  roles:
    - comfy
    - knows_me
    - hardened
    - kubed

- name: Setup zfs on storage array
  hosts: homelab-mainarray
  become: true
  vars_files:
    - ./vars/zfs.yml
  roles:
    - storage_array

- name: Setup main array as head
  hosts: homelab-mainarray
  become: true
  vars_files:
    - ./vars/k3s.yml
  roles:
    - kubed_head
