# Has my account & relevant details
---
- name: create main user
  ansible.builtin.user:
    name: kwkaiser
    state: present
    comment: Karl's account
    shell: /bin/bash
    append: true
    groups:
      - sudo

- name: create ssh dir if missing
  ansible.builtin.file:
    dest: /home/kwkaiser/.ssh
    mode: '0700'
    state: directory 
    owner: kwkaiser
    group: kwkaiser

- name: create keys dir if missing
  ansible.builtin.file:
    dest: /home/kwkaiser/.ssh/authorized_keys
    mode: '0600'
    state: touch
    owner: kwkaiser
    group: kwkaiser

- name: copy homelab ssh key content
  ansible.builtin.lineinfile:
    path: /home/kwkaiser/.ssh/authorized_keys
    regexp: '.*'
    line: "{{box_pubkey}}\n"