---
- name: remove swapfile from /etc/fstap
  ansible.builtin.mount:
    fstype: swap
    state: absent
    name: 
      - swap
      - none

- name: disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: rm config
  notify: restart containerd
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: touch

- name: wait for containerd to start
  ansible.builtin.service:
    name: containerd
    state: started
  register: myserviceDetails
  until: myserviceDetails.status.ActiveState == "active"
  retries: 15
  delay: 5 

- name: add apt key for k8s 
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add repo for k8s
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: install k8s binaries
  apt: 
    state: present
    update_cache: yes
    name: 
      - kubelet
      - kubeadm
      - kubectl

- name: configure node ip
  lineinfile:
    path: /etc/default/kubelet
    create: yes
    line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_host }}

- name: start kubelet 
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: true
    enabled: true
    state: restarted