---
- name: Create cluster with kubeadm
  ansible.builtin.command: >
    kubeadm init
    --apiserver-advertise-address="{{ ansible_host }}"
    --apiserver-cert-extra-sans="{{ ansible_host }}"
    --node-name "{{ ansible_hostname }}"
    --pod-network-cidr='10.244.0.0/16'
  args:
    creates: /etc/kubernetes/admin.conf
