---
- name: Download K3s script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    mode: 'a+x'
    dest: /home/ansible/k3s.sh

- name: Setup server
  ansible.builtin.command: sh -s /home/ansible/k3s.sh
  environment:
    INSTALL_K3S_EXEC: "server --node-ip {{ ansible_host }} --node-external-ip {{ ansible_host }} --kubelet-arg=allowed-unsafe-sysctls=net.ipv4.conf.all.src_valid_mark,net.ipv6.conf.all.disable_ipv6"
  args:
    creates: /etc/rancher/k3s/k3s.yaml

- name: Replace IP address
  ansible.builtin.replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: '127\.0\.0\.1:6443'
    replace: "{{ ansible_host }}:6443"

- name: Get node token
  ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
  register: token_output

- name: Set join token
  ansible.builtin.set_fact:
    join_token: "{{ token_output.stdout }}"
    join_server: "{{ ansible_host }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

- name: Label head
  ansible.builtin.command: kubectl label nodes homelab-thinkcentre head=true
