---
- name: Allow pods on control plane (if configured).
  ansible.builtin.command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  register: kubernetes_taint
  args:
    creates: /etc/kubernetes/taint.step

- name: Denote success of prev step
  ansible.builtin.file:
    path: /etc/kubernetes/taint.step
    state: touch
    mode: "0755"
  when: kubernetes_taint.rc == 0
