# Ensure that hosts have required commonly used CLI utils
- name: Install cli utils
  ansible.builtin.package:
    state: present
    update_cache: yes
    name:
      - htop
      - fzf
      - tldr
      - vim
      - jq
      - nfs-common

- name: Install yq from src
  ansible.builtin.get_url:
    url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    dest: /usr/bin/yq
    mode: 'a+x'

- name: Install networking utils
  ansible.builtin.package:
    state: present
    name:
      - curl

- name: Install additional ansible utils
  ansible.builtin.package:
    name:
      - python3-netaddr
      - acl

- name: Install system utils
  ansible.builtin.package:
    state: present
    name:
      - gnupg
      - ca-certificates
      - lsb-release
