name: Deploy

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          apt update
          apt install ansible --assume-yes
          apt install ansible-lint --assume-yes

      - name: Install ansible galaxy deps
        run: make install

      - name: Lint
        run: ansible-lint
  
  deploy:
    name: Perform dry run
    needs: code-quality
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          apt update
          apt install ansible --assume-yes
          apt install ansible-lint --assume-yes

      - name: Install galaxy deps
        run: make install 

      - name: Run playbook
        run: |
          eval $(ssh-agent -s)
          echo "$ANSIBLE_KEY" | ssh-add -
          ansible-playbook -i inv/prod setup-lab.yml
        env:
          ANSIBLE_KEY: ${{ secrets.ANSIBLE_KEY }}
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}