name: Deploy

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          apt update
          apt install ansible --assume-yes
          apt install ansible-lint --assume-yes

      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d 

      - name: foo
        run: ansible-galaxy role list 2>/dev/null

      - name: Install ansible galaxy deps
        run: ./bin/task install

      - name: Lint
        run: ./bin/task lint
  
  deploy:
    name: Deploy
    needs: code-quality
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          apt update
          apt install ansible --assume-yes

      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d 

      - name: Install galaxy deps
        run: ./bin/task install

      - name: Run playbook
        run: |
          eval $(ssh-agent -s)
          echo "$ANSIBLE_KEY" | ssh-add -
          ansible-playbook -i inv/prod setup-lab.yml
        env:
          ANSIBLE_KEY: ${{ secrets.ANSIBLE_KEY }}
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}