name: Deploy

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          apt update
          apt install ansible --assume-yes
          apt install ansible-lint --assume-yes

      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d 

      - name: Install ansible galaxy deps
        run: ./bin/task install

      - name: Lint
        run: ./bin/task lint
  
