name: Deploy

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Check code quality
    uses: ./.gitea/workflows/code-quality.yaml 

  
  deploy:
    name: Perform dry run
    needs: code-quality
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          apt update
          apt install ansible --assume-yes
          apt install ansible-lint --assume-yes

      - name: Install galaxy deps
        run: make install 

      - name: Run playbook
        run: |
          eval $(ssh-agent -s)
          echo "$ANSIBLE_KEY" | ssh-add -
          echo $(ssh-add -l)
          ansible -i inv/prod mainarray -m shell -a "echo 'testing echo'"
          # ansible-playbook -i inv/prod --check setup-lab.yml
        env:
          ANSIBLE_KEY: ${{ secrets.ANSIBLE_KEY }}