name: Pull request

on:
  pull_request_target:
    branches:
      - '**'

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            ref: ${{ github.event.pull_request.head.sha }}      

      - name: Install ansible
        run: |
          apt update
          apt install ansible --assume-yes
          apt install ansible-lint --assume-yes

      - name: Install ansible galaxy deps
        run: make install

      - name: Lint
        run: ansible-lint