###########
# Ansible #
###########

ansible_user: kwkaiser

#######
# ZFS #
#######

zfs_volumes:
  - name: nfs
    pool: bulk-pool
    state: present

zfs_pools:
  - name: bulk-pool
    action: create
    compression: lz4
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdd
      - /dev/sdf
    type: raidz2
    state: present

#######
# K3s #
#######

master_ip: 192.168.2.103
extra_server_args: "--no-deploy traefik --kubelet-arg=allowed-unsafe-sysctls=net.ipv6.conf.all.forwarding,net.ipv4.conf.all.src_valid_mark,net.ipv6.conf.all.disable_ipv6,net.ipv4.ip_forward"
extra_agent_args: "--no-deploy traefik --kubelet-arg=allowed-unsafe-sysctls=net.ipv6.conf.all.forwarding,net.ipv4.conf.all.src_valid_mark,net.ipv6.conf.all.disable_ipv6,net.ipv4.ip_forward"

###########
# Secrets #
###########

ansible_become_pass: "{{ lookup('env', 'SUDO_PASSWORD') }}"
