# Ensure hosts have docker installed & enabled
---
- name: add docker key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/debian/gpg"

- name: install docker
  ansible.builtin.apt:
    update_cache: true
    state: present
    name:
      - docker 
      - docker-compose

- name: enable docker
  ansible.builtin.systemd:
    name: docker
    daemon_reload: true
    enabled: true
    state: started