# Harden / remove networking access
---
- name: Remove ssh root access
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "sshd -t -f %s"
  with_items:
    - regexp: "^#PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#PubkeyAuthentication"
      line: "PubkeyAuthentication yes"
    - regexp: "^#PermitRootLogin"
      line: "PermitRootLogin no"
  notify: Restart ssh

- name: Add sudo rights for main user
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^kwkaiser"
    line: "kwkaiser ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: "visudo -cf %s"

- name: Install wireguard
  ansible.builtin.apt:
    state: present
    update_cache: true
    name: wireguard

- name: Install fail2ban
  ansible.builtin.apt:
    state: present
    update_cache: true
    name: fail2ban

- name: Enable fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    daemon_reload: true
    enabled: true
    state: started

- name: Install ufw
  ansible.builtin.apt:
    state: present
    update_cache: true
    name: ufw

- name: Allow ssh in ufw
  community.general.ufw:
    comment: ssh
    rule: allow
    port: 22

- name: Enable ufw (systemd)
  ansible.builtin.systemd:
    name: ufw
    daemon_reload: true
    enabled: true
    state: started

- name: Enable ufw (ufw)
  community.general.ufw:
    state: enabled
