---
- hosts: all
  name: Setup common utils shared on all
  become: true
  roles:
    - knows_me
    - hardened
    - comfy

# - hosts: homelab-mainarray
#   name: setup zfs on storage array
#   become: true
#   vars_files:
#     - zfs.yml
#   roles:
#     - mrlesmithjr.zfs

- hosts: heads
  name: Setup kubernetes cluster head
  become: true
  roles:
    - kubed_head

- hosts: nodes
  name: Setup kubernetes cluster nodes
  become: true
  roles:
    - kubed_node
