# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian10"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  config.vm.define "paprika" do |sys|
    sys.vm.hostname = "paprika"
    sys.vm.network :private_network, ip: "192.168.56.68"
  end

  config.vm.define "coriander" do |sys|
    sys.vm.hostname = "coriander"
    sys.vm.network :private_network, ip: "192.168.56.69"
  end

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "setup-lab.yml"
  end
end
