---
- name: initialize k8s cluster using kubeadm
  command: >
    kubeadm init \
      --apiserver-advertise-address={{ ansible_default_ipv4.address }} \
      --apiserver-cert-extra-sans={{ ansible_default_ipv4.address }} \
      --node-name paprika \
      --pod-network-cidr=192.168.56.0/8

- name: setup kubeconfig for main user
  shell: | 
    mkdir -p /home/vagrant/.kube
    cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config  