---
- name: determine env
  set_fact:
    dev: "{{ env is match('dev') }}"
    prod: "{{ env is match('prod') }}"
    test: "{{ env is match('test') }}"

- name: print env
  debug: 
    msg: "Using environment {{ env }}: (dev, {{dev}}), (test, {{test}}), (prod, {{prod}})"

- name: set dev vars
  when: dev|bool
  set_fact:
    keepass_path: "{{ lookup('env', 'HOME') }}/documents/keys/keys.dbx"

- name: set dev vars
  when: prod or test 
  set_fact:
    keepass_path: "{{ playbook_dir }}/keys.dbx"
