---
- name: Determine env from environment
  ansible.builtin.command: "echo {{ lookup('env', 'ANSIBLE_ENV') }}"
  register: env

- name: Determine env
  ansible.builtin.set_fact:
    dev: "{{ env is match('dev') }}"
    prod: "{{ env is match('prod') }}"
    test: "{{ env is match('test') }}"

- name: Print env
  ansible.builtin.debug:
    msg: "Using environment {{ env }}: (dev, {{ dev }}), (test, {{ test }}), (prod, {{ prod }})"

- name: Set dev vars
  when: dev|bool
  ansible.builtin.set_fact:
    keepass_path: "{{ lookup('env', 'HOME') }}/documents/keys/keys.dbx"

- name: Set dev vars
  when: prod or test
  ansible.builtin.set_fact:
    keepass_path: "{{ playbook_dir }}/keys.dbx"

- name: Include secrets
  ansible.builtin.include_vars:
    file: devtest-secrets.yml
